root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/main ./src"
  bin = "./bin/main"
  delay = 1000
  include_dir = ["src"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]