version: v0.10.1
formatter: default
rules:
  - header-min-length
  - header-max-length
  - body-max-line-length
  - footer-max-line-length
  - type-enum
severity:
  default: error
settings:
  body-max-length:
    argument: -1
  body-max-line-length:
    argument: 72
  body-min-length:
    argument: 0
  description-max-length:
    argument: -1
  description-min-length:
    argument: 0
  footer-enum:
    argument: []
  footer-max-length:
    argument: -1
  footer-max-line-length:
    argument: 72
  footer-min-length:
    argument: 0
  footer-type-enum:
    argument: []
  header-max-length:
    argument: 50
  header-min-length:
    argument: 10
  scope-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/,
  scope-enum:
    argument:
      - assets
      - components
      - atoms
      - molecules
      - organisms
      - configs
      - contexts
      - enums
      - hooks
      - pages
      - queries
      - routes
      - services
      - utils
      - main
    flags:
      allow-empty: true
  scope-max-length:
    argument: -1
  scope-min-length:
    argument: 0
  type-charset:
    argument: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  type-enum:
    argument:
      - bump
      - chore
      - docs
      - e2e
      - feat
      - fix
      - optimize
      - refactor
      - revamp
      - revert
      - security
      - style
      - test
  type-max-length:
    argument: -1
  type-min-length:
    argument: 0
